### ISSUE TITLE
How to Connect & Migrate with Postgress

### ISSUE THREAD

**Issue by MuthuNellai** [halilkocaoz/miny-todo#2]
Hi,

How to Connect & Migrate with Postgress..
If any Specific Command for Database Migration

**Comment by halilkocaoz** [comment]
please check [appsettings.Development.json](https://github.com/halilkocaoz/miny-todo-nlayer/blob/main/MinyToDo.WebAPI/appsettings.Development.json) to connect database, and I added a section about migration at [README.md](https://github.com/halilkocaoz/miny-todo-nlayer/blob/main/README.md)

**Comment by halilkocaoz** [comment]
hey @MuthuNellai,

please check [appsettings.Development.json](https://github.com/halilkocaoz/miny-todo-nlayer/blob/main/MinyToDo.WebAPI/appsettings.Development.json) to connect database, and I added a section about migration at [README.md](https://github.com/halilkocaoz/miny-todo-nlayer/blob/main/README.md)
